### PR TITLE
test: Telemetry OTLP-based components error/warning logs

### LINKED ISSUE #844: Test for error logs of active components
**Description**
Several times we missed that telemetry components are having error logs, especially in the startup phase. It will be valuable to have a test case which assures that for the regular cases, no new error logs are getting produced in any component.

**Criterias**
- All pipelines are running with all features switched on
- Not a single component of the module is producing any error log
- If there is an error log, a test case should fail

### PR DESCRIPTION
**Pull request by TeodorSAP**
## Description

Changes proposed in this pull request (what was done and why):

- OTLP-based telemetry components error/warning logs e2e test
- A new e2e test label and GH pipeline, called "telemetry-logs-analysis", for referring to tests that analyze telemetry components' logs
- TODO: Check FluentBit-based components, adding a new feature flag to LogPipeline (upcoming PR)

Changes refer to particular issues, PRs or documents:

- Resolves #844 

## Traceability
- [ ] The PR is linked to a GitHub issue.
- [ ] New features have a milestone set.
- [ ] New features have defined acceptance criteria in a corresponding GitHub Issue, and all criteria are satisfied with this PR.
- [ ] The corresponding GitHub issue has a respective `area` and `kind` label.
- [ ] The follow-up issues (if any) are linked in the `Related Issues` section.
- [ ] Adjusted the documentation if the change is user-facing.
- [ ] The feature is unit-tested
- [ ] The feature is e2e-tested

### CODE REVIEW

File: test/testkit/matchers/log/log_matchers.go [hunk 1]
```diff
@@ -133,3 +133,9 @@ func WithLogRecordAttrs(matcher types.GomegaMatcher) types.GomegaMatcher {
 		return lr.Attributes().AsRaw()
 	}, matcher)
 }
+
+func WithLogBody(matcher types.GomegaMatcher) types.GomegaMatcher {
+	return gomega.WithTransform(func(lr plog.LogRecord) string {
+		return lr.Body().AsString()
+	}, matcher)
+}
```
Comment (skhalash) [inline test/testkit/matchers/log/log_matchers.go:141]: Please add a unit test for this matcher. You can draw inspiration from the other unit tests in that package :)

**Comment by TeodorSAP** [comment]
This is how the error/warning logs will be displayed (without gomega truncation) if something pops up.
[4_Run tests.txt](https://github.com/kyma-project/telemetry-manager/files/14855406/4_Run.tests.txt)

**Review by skhalash — APPROVED** [review]
